urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin
from fae import views, utils
from registration.forms import RegistrationFormUniqueEmail
from registration.views import register

admin.autodiscover()

urlpatterns = patterns(
    '',
    # Default page
    (r'^$', views.index),
    (r'^multi/$', views.index_multi),

    # Debugging
    (r'^sysinfo/$', utils.sysinfo),
    (r'^urltest/$', utils.urltest),

    # Report pages
    (r'^report/([0-9a-f]{16})/$', views.report),
    (r'^report/([0-9a-f]{16})/(summary|sitewide|page|menu|urls|xml)/$', views.report),
    (r'^report/([0-9a-f]{16})/(sitewide)/([a-z]+)/$', views.report),
    (r'^report/([0-9a-f]{16})/(page)/(\d+)/$', views.page_report),
    (r'^report/([0-9a-f]{16})/(page)/(\d+)/([a-z]+)/$', views.page_report),

    # Accessibility Extension
    (r'^evaluate/dhtml/$', views.process_dhtml),

    # Direct link to FAE
    (r'^evaluate/link/$', views.process_link),

    # List of page evals for Sitewide Report
    (r'^pgrpteval/$', views.pgrpteval),

    # Report archive
    (r'^reports/archive/$', views.archived_reports),
    (r'^reports/manage/$', views.manage_reports),

    # About FAE
    (r'^about/$', views.about),
    (r'^about/(\w+)/$', views.about),

    # User profile
    (r'^accounts/profile/$', views.my_account),

    # Admin
    (r'^admin/(.*)', admin.site.root),
)

if settings.ALLOW_REGISTRATION:
    urlpatterns += patterns(
        '',
        # Require unique email address by specifying form_class
        (r'^accounts/register/$', register, {'form_class': RegistrationFormUniqueEmail}, 'registration_register'),
    )
else:
    urlpatterns += patterns(
        '',
        # Override register URL in registration.urls
        (r'^accounts/register/$', views.registration_closed),
    )

urlpatterns += patterns(
    '',
    # Override logout URL in registration.urls
    (r'^accounts/logout/$', views.logout),

    # Registration app (includes account management)
    (r'^accounts/', include('registration.urls')),
)

fae/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
import os
import subprocess

# rm commands in two flavors
user_rm = ['rm', '-f']
sudo_rm = ['sudo', '-u', 'apache'] + user_rm

def remove_file(filename):
    # If running under apache, user_rm works okay.
    cmd = user_rm
    cmd.append(filename)
    retval = subprocess.call(cmd)
    if retval == 0: return
    # Need sudo_rm command with standalone script.
    cmd = sudo_rm
    cmd.append(filename)
    subprocess.call(cmd)

# The built-in Django User relation:

#class User(models.Model):
#   username      = models.CharField(max_length=30, unique=True)
#   first_name    = models.CharField(max_length=30, blank=True)
#   last_name     = models.CharField(max_length=30, blank=True)
#   email         = models.EmailField(blank=True)
#   password      = models.CharField(max_length=128)
#   is_staff      = models.BooleanField(default=False)
#   is_active     = models.BooleanField(default=True)
#   is_superuser  = models.BooleanField(default=False)
#   last_login    = models.DateTimeField()
#   date_joined   = models.DateTimeField()

# Custom classes for FAE

class Organization(models.Model):
    ORG_TYPE_CHOICES = (
        (1, 'Other'),
        (2, 'Level 2'),
        (3, 'Level 3'),
        (4, 'Level 4'),
        (5, 'Partner'),
    )

    name          = models.CharField(max_length=128)
    org_type      = models.IntegerField(choices=ORG_TYPE_CHOICES)
    url           = models.URLField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ["name"]

class UserProfile(models.Model):
    ACCT_TYPE_CHOICES = (
        (1, 'Standard'),
        (2, 'Level 2'),
        (3, 'Level 3'),
        (4, 'Level 4'),
        (5, 'Maximum'),
    )

    user          = models.ForeignKey(User, unique=True)
    acct_type     = models.IntegerField(choices=ACCT_TYPE_CHOICES, default=1)
    org           = models.ForeignKey(Organization)

    def __unicode__(self):
        return self.user.username

class EmailSuffix(models.Model):
    suffix        = models.CharField(max_length=128, primary_key=True)
    org           = models.ForeignKey(Organization)

    def __unicode__(self):
        return self.suffix

    class Meta:
        ordering = ["suffix"]

class UserReport(models.Model):
    id            = models.CharField(max_length=30, primary_key=True)
    user          = models.ForeignKey(User)
    timestamp     = models.DateTimeField()
    pgcount       = models.IntegerField()
    url           = models.URLField()
    urlcount      = models.IntegerField()
    depth         = models.IntegerField()
    title         = models.CharField(max_length=128, blank=True)
    archive       = models.BooleanField(default=False)
    stats         = models.BooleanField(default=False)
    dhtml         = models.BooleanField(default=False)

    def __unicode__(self):
        return self.id

    def get_absolute_url(self):
        return '/report/%s/summary/' % self.id

    def get_filename(self):
        return os.path.join(settings.USER_REPORTS_DIR, self.id + '.xml')

    def remove_results_file(self):
        remove_file(self.get_filename())

    class Meta:
        ordering = ["-timestamp"]

class GuestReport(models.Model):
    id            = models.CharField(max_length=30, primary_key=True)
    timestamp     = models.DateTimeField()
    pgcount       = models.IntegerField()
    url           = models.URLField()
    stats         = models.BooleanField(default=False)
    dhtml         = models.BooleanField(default=False)

    def __unicode__(self):
        return self.id

    def get_filename(self):
        return os.path.join(settings.GUEST_REPORTS_DIR, self.id + '.xml')

    def remove_results_file(self):
        remove_file(self.get_filename())

    class Meta:
        ordering = ["-timestamp"]

class UsageStats(models.Model):
    date          = models.DateField(primary_key=True)
    user_reports  = models.IntegerField()
    user_pgcount  = models.IntegerField()
    guest_reports = models.IntegerField()
    guest_pgcount = models.IntegerField()
    depth_1       = models.IntegerField()
    depth_2       = models.IntegerField()

    class Meta:
        get_latest_by = "date"
        ordering = ["date"]

fae/views.py
from django.template.loader import get_template
from django.template import RequestContext
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from datetime import datetime, date, timedelta

from project.settings import ACCT_TYPE_QUOTA, DEFAULT_QUOTA, ACCT_TYPE_BUFFER, DEFAULT_BUFFER
from project.settings import STATS_DAYS_OFFSET as DAYS_OFFSET
from labels import labels
from models import UserProfile, UserReport, GuestReport, UsageStats
from forms import BasicEvalForm, DepthEvalForm, MultiEvalForm
from forms import UserForm, ProfileForm, ManageReportForm
from evaluate import evaluate, multi_evaluate, evaluate_dhtml
from processors import get_report_content, get_pgrpteval_content
from uid import generate

#----------------------------------------------------------------
def index(request):
    """
    Serve the appropriate Run FAE form based on the user's login status.
    """
    if request.user.is_authenticated():
        return index_user(request)
    else:
        return index_guest(request)

#----------------------------------------------------------------
def index_user(request):

    # Create response object for saving cookie values
    response = HttpResponse()

    if request.method == 'POST':
        form = DepthEvalForm(request.POST)
        if form.is_valid():
            # Check that formid matches session variable
            if not check_formid(request):
                raise Http404(labels['invalid_formid'])
            params = {
                'url': form.cleaned_data['url'],
                'title': form.cleaned_data['title'] or labels['untitled'],
                'depth': form.cleaned_data['depth'],
                'span': form.cleaned_data['span'],
                'dhtml': form.cleaned_data['dhtml'] and settings.ENABLE_DHTMLGET,
                'username': request.user.username
                }
            now = datetime.now()
            status, uid = evaluate(params, request.user.is_authenticated(), now)
            if status:
                report = UserReport(
                    id = uid,
                    user = request.user,
                    timestamp = now,
                    pgcount = status,
                    url = params['url'],
                    urlcount = 1,
                    depth = params['depth'],
                    title = params['title'],
                    dhtml = params['dhtml']
                    )
                report.save()
                response = HttpResponseRedirect('/report/%s/' % uid)

            # Set cookie values on whichever response object we have
            response.set_cookie('d_url', value=form.cleaned_data['url'], max_age=settings.MAX_AGE)
            response.set_cookie('d_title', value=form.cleaned_data['title'], max_age=settings.MAX_AGE)
            response.set_cookie('d_depth', value=form.cleaned_data['depth'], max_age=settings.MAX_AGE)
            response.set_cookie('d_span', value=form.cleaned_data['span'], max_age=settings.MAX_AGE)
            if form.cleaned_data['dhtml']:
                response.set_cookie('d_dhtml', value=form.cleaned_data['dhtml'], max_age=settings.MAX_AGE)
            else:
                response.delete_cookie('d_dhtml')

            if status:
                return response
            else:
                return message(request, response, 'Unable to create report!')

    else:
        init_values = {}
        if 'd_url' in request.COOKIES:
            init_values['url'] = request.COOKIES['d_url']
        if 'd_title' in request.COOKIES:
            init_values['title'] = request.COOKIES['d_title']
        if 'd_depth' in request.COOKIES:
            init_values['depth'] = request.COOKIES['d_depth']
        if 'd_span' in request.COOKIES:
            init_values['span'] = request.COOKIES['d_span']
        if 'd_dhtml' in request.COOKIES:
            init_values['dhtml'] = request.COOKIES['d_dhtml']
        form = DepthEvalForm(initial=init_values)

    context = {
        'page_type': 'index',
        'title': labels['index'],
        'formid': store_formid(request),
        'form': form,
        }

    # Return response
    t = get_template('index_user.html')
    html = t.render(RequestContext(request, context))
    response.write(html)
    return response

#----------------------------------------------------------------
def index_guest(request):

    # Create response object for saving cookie values
    response = HttpResponse()

    if request.method == 'POST':
        form = BasicEvalForm(request.POST)
        if form.is_valid():
            # Check that formid matches session variable
            if not check_formid(request):
                raise Http404(labels['invalid_formid'])
            params = {
                'url': form.cleaned_data['url'],
                'title': labels['untitled'],
                'dhtml': form.cleaned_data['dhtml'] and settings.ENABLE_DHTMLGET,
                'username': 'guest'
                }
            now = datetime.now()
            status, uid = evaluate(params, False, now)
            if status:
                report = GuestReport(
                    id = uid,
                    timestamp = now,
                    pgcount = status,
                    url = params['url'],
                    dhtml = params['dhtml']
                    )
                report.save()
                response = HttpResponseRedirect('/report/%s/' % uid)

            response.set_cookie('b_url', value=form.cleaned_data['url'], max_age=settings.MAX_AGE)
            if form.cleaned_data['dhtml']:
                response.set_cookie('b_dhtml', value=form.cleaned_data['dhtml'], max_age=settings.MAX_AGE)
            else:
                response.delete_cookie('b_dhtml')

            if status:
                return response
            else:
                return message(request, response, 'Unable to create report!')
    else:
        init_values = {}
        if 'b_url' in request.COOKIES:
            init_values['url'] = request.COOKIES['b_url']
        if 'b_dhtml' in request.COOKIES:
            init_values['dhtml'] = request.COOKIES['b_dhtml']
        form = BasicEvalForm(initial=init_values)

    context = {
        'page_type': 'index',
        'title': labels['index'],
        'formid': store_formid(request),
        'form': form,
        }

    # Return response
    t = get_template('index_guest.html')
    html = t.render(RequestContext(request, context))
    response.write(html)
    return response

#----------------------------------------------------------------
@login_required
def index_multi(request):

    # Create response object for saving cookie values
    response = HttpResponse()

    if request.method == 'POST':
        form = MultiEvalForm(request.POST)
        if form.is_valid():
            # Check that formid matches session variable
            if not check_formid(request):
                raise Http404(labels['invalid_formid'])
            params = {
                'urls': form.cleaned_data['urls'],
                'title': form.cleaned_data['title'] or labels['untitled'],
                'dhtml': form.cleaned_data['dhtml'] and settings.ENABLE_DHTMLGET,
                'username': request.user.username
                }
            now = datetime.now()
            status, uid = multi_evaluate(params, request.user.is_authenticated(), now)

            if status:
                urls = form.cleaned_data['urls'].split()
                report = UserReport(
                    id = uid,
                    user = request.user,
                    timestamp = now,
                    pgcount = status,
                    url = urls[0],
                    urlcount = len(urls),
                    depth = 0,
                    title = params['title'],
                    dhtml = params['dhtml']
                    )
                report.save()
                response = HttpResponseRedirect('/report/%s/' % uid)

            response.set_cookie('m_urls', value=form.cleaned_data['urls'], max_age=settings.MAX_AGE)
            response.set_cookie('m_title', value=form.cleaned_data['title'], max_age=settings.MAX_AGE)
            if form.cleaned_data['dhtml']:
                response.set_cookie('m_dhtml', value=form.cleaned_data['dhtml'], max_age=settings.MAX_AGE)
            else:
                response.delete_cookie('m_dhtml')

            if status:
                return response
            else:
                return message(request, response, 'Unable to create report!')
    else:
        init_values = {}
        if 'm_urls' in request.COOKIES:
            init_values['urls'] = request.COOKIES['m_urls']
        if 'm_title' in request.COOKIES:
            init_values['title'] = request.COOKIES['m_title']
        if 'm_dhtml' in request.COOKIES:
            init_values['dhtml'] = request.COOKIES['m_dhtml']
        form = MultiEvalForm(initial=init_values)

    context = {
        'page_type': 'index',
        'title': labels['multi'],
        'formid': store_formid(request),
        'form': form,
        }

    # Return response
    t = get_template('index_multi.html')
    html = t.render(RequestContext(request, context))
    response.write(html)
    return response

#----------------------------------------------------------------
def process_dhtml(request):
    """
    Evaluate one or more DHTML DOM snapshots sent as POST data.
    """
    if not request.method == 'POST':
        raise Http404('Unable to process DHTML data!')

    if 'doc1' in request.POST and len(request.POST['doc1']):
        params = {
            'request': request,
            'url': 'Unspecified',
            'depth': '0',
            'title': 'DHTML Report',
            'dhtml':  settings.ENABLE_DHTMLGET,
            'username': request.user.username
            }
        now = datetime.now()

fae/templates/archive.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }}</h1>

{% if report_list %}
<table cellpadding="0" cellspacing="0" class="archive" summary="Archived Reports Table">
<tr class="row-highlight">
    <th class="archive-0">Perm.</th>
    <th class="archive-1">Report Title</th>
    <th class="archive-2">Date/Time</th>
    <th class="archive-3">Pages</th>
    {% if enable_dhtmlget %}
    <th class="archive-4">DHTML</th>
    {% endif %}
    <th class="archive-5">URL</th>
    <th class="archive-6">Depth</th>
</tr>
{% for report in report_list %}
<tr{% if forloop.counter|divisibleby:"2" %} class="row-highlight"{% endif %}>
<td class="archive-0{% ifequal report.id current_id %} selected{% endifequal %}" style="text-align: center">{% if report.archive %}Y{% endif %}</td>
<td class="archive-1{% ifequal report.id current_id %} selected{% endifequal %}"><a href="{{ report.get_absolute_url }}">{{ report.title }}</a></td>
<td class="archive-2{% ifequal report.id current_id %} selected{% endifequal %}">{{ report.timestamp|date:"Y-m-d H:i"}}</td>
<td class="archive-3{% ifequal report.id current_id %} selected{% endifequal %}">{{ report.pgcount }}</td>
{% if enable_dhtmlget %}
<td class="archive-4{% ifequal report.id current_id %} selected{% endifequal %}">{% if report.dhtml %}Y{% endif %}</td>
{% endif %}
<td class="archive-5{% ifequal report.id current_id %} selected{% endifequal %}">{{ report.url }}{% ifnotequal report.urlcount 1 %} ...{% endifnotequal %}</td>
<td class="archive-6{% ifequal report.id current_id %} selected{% endifequal %}">{{ report.depth }}</td>
</tr>
{% endfor %}
</table>
{% else %}
<p>No reports are currently archived for <strong>{{ username }}</strong>.</p>
{% endif %}

{% endblock %}

fae/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-us" xml:lang="en-us">
<head>
{% block title %}<title>{{ site.name }}: {{ title }}</title>{% endblock %}
<meta name="author" content="Nicholas Hoyt"/>
<meta name="description" content="{{ site.name }}: {{ title }}"/>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" href="/media/css/fae_screen.css" type="text/css"/>
<link rel="stylesheet" href="/media/css/fae_django.css" type="text/css"/>
<link rel="stylesheet" href="/media/css/fae_print.css" type="text/css" media="print"/>
<link rel="shortcut icon" href="/media/images/favicon.ico" type="image/x-icon"/>
<!--[if IE]>
<style type="text/css">
#header div.subheader { padding: 0.25em 0 0.5em 0; }
#header div.subheader ul.top-menu { padding-right: 1em; }
</style>
<![endif]-->
{% block javascript %}
<script type="text/javascript">
/* Define getElement() for browsers new and old. */
if (document.getElementById) {
    getElement = function(id) { return document.getElementById(id); }
} else if (document.all) {
    getElement = function(id) { return document.all[id]; };
} else if (document.layers) {
    getElement = function(id) { return document.layers[id]; };
} else {
    getElement = function() { return null; }
}
function enable(id) {
  var widget = getElement(id);
  widget.disabled = false;
}
function disable(id) {
  var widget = getElement(id);
  widget.disabled = true;
}
function decode(id) {
  var prefix = "Email: ";
  var linkText = "Contact Us";

  // get the encoded element if it exists
  var srcNode = getElement(id);
  if (!srcNode) { return; }

  // decode the address
  var address = srcNode.firstChild.nodeValue;
  address = address.replace(prefix, "");
  address = address.replace(/ at /, "@");
  address = address.replace(/ dot /g, ".");

  // construct the decoded link element
  var tgtNode = document.createElement("a");

  var hrefAttr = document.createAttribute("href");
  hrefAttr.value = "mailto:" + address;
  tgtNode.setAttributeNode(hrefAttr);

  var textNode = document.createTextNode(linkText);
  tgtNode.appendChild(textNode);

  // get parent node of encoded element
  var prnt = srcNode.parentNode;
  prnt.replaceChild(tgtNode, srcNode);
}
</script>
{% endblock %}
</head>
{% block bodytag %}<body onload="decode('contact')">{% endblock %}
<!-- header -->
<div id="header">
<div class="left"><a href="/"><img src="/media/images/fae_logo.gif" alt="fae"/></a></div>
<div class="subtitle"><span class="large">Functional Accessibility Evaluator {{ version }}</span><br />University of Illinois at Urbana-Champaign</div>
<div id="uiuc"><img alt="University of Illinois logo" src="/media/images/uiuc_logo.jpg"/></div>
<div class="subheader">
<h2 class="hidden">Navigation: Utilities</h2>
<ul class="top-menu">
<li><a href="/about/">About FAE</a></li>
{% if user.is_authenticated %}
<li><span class="separator">|</span><a href="/multi/">Multiple URLs</a></li>
<li><span class="separator">|</span><a href="/accounts/profile/">My Account</a></li>
<li><span class="separator">|</span><a href="/accounts/logout/">Log Out: {{ user.username }}</a></li>
{% else %}
<li><span class="separator">|</span><a href="/accounts/register/">Register</a></li>
<li><span class="separator">|</span><a href="/accounts/login/?next=/">Log In</a></li>
{% endif %}
</ul>
</div>
</div>
<!-- sidebar -->
{% block sidebar %}{% include "sidebar.html" %}{% endblock %}
<!-- main content -->
<div id="main">
{% block content %}{% endblock %}
</div>
<!-- footer -->
<div id="footer">
<hr />
Copyright &copy; 2005&ndash;{% now "Y" %}, University of Illinois.  All rights reserved.
<span class="separator">|</span><span id="contact">Email: {{ contact_email }}</span>
<span class="separator">|</span><a href="http://www.vpaa.uillinois.edu/policies/web_privacy.asp?bch=1">Privacy Policy</a>
<span class="separator">|</span><a href="/about/disclaimer/">Disclaimer</a>
{% if test_install %}
<span class="separator">|</span><a href="http://validator.w3.org/check/referer">W3C HTML Validator</a>
{% endif %}
</div>
{% comment %}
<!--
<script src="http://www.google-analytics.com/urchin.js" type="text/javascript"></script>
<script type="text/javascript">
_uacct = "UA-1064834-1";
urchinTracker();
</script>
-->
{% endcomment %}
</body>
</html>

fae/templates/dhtml_note.html
<p>Note: Selecting the following option may result in longer evaluation times. See <a href="/about/#running_the_evaluator">About FAE: Running the Evaluator</a> for more information.</p>

fae/templates/index_guest.html
{% extends "base.html" %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
function initDoc() {
  var url = getElement('id_url');
  if (url) { url.focus(); }
}
</script>
{% endblock %}

{% block bodytag %}<body onload="initDoc(); decode('contact')" onunload="enable('submit')">{% endblock %}

{% block content %}
<h1>{{ title }}</h1>
<div>
<p>Use this form to evaluate the functional accessibility of a single web page.</p>
<p><a href="/accounts/register/">Register for a free user account</a>
to gain access to these additional features:</p>
<ul>
<li>Evaluate multiple pages via web crawling</li>
<li>Generate a Sitewide Report that identifies problem pages</li>
<li>Save reports in an account-specific Archived Reports list</li>
</ul>
</div>

<form action="." method="post" onsubmit="disable('submit')">

<div class="urls">
{% if form.url.errors %}{{ form.url.errors }}{% endif %}
{{ form.url.label_tag }}<br/>{{ form.url }}
</div>

{% if enable_dhtmlget %}
<div class="radio-btns">
{% if form.dhtml.errors %}{{ form.dhtml.errors }}{% endif %}
{{ form.dhtml }} {{ form.dhtml.label_tag }}
</div>
{% endif %}

<div class="submit">
<input type="submit" id="submit" value="Evaluate"/>
</div>

<div>
<input type="hidden" name="formid" value="{{ formid }}"/>
</div>

</form>
{% endblock %}

fae/templates/index_multi.html
{% extends "base.html" %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript">
function initDoc() {
  var url = getElement('id_urls');
  if (url) { url.focus(); }
}
</script>
{% endblock %}

{% block bodytag %}<body onload="initDoc(); decode('contact')" onunload="enable('submit')">{% endblock %}

{% block content %}
<h1>{{ title }}</h1>
<div>
<p>Use this form to evaluate the functional accessibility of one or more web pages.</p>

<div class="notes">
<ul>
<li>Enter multiple URLs one per line or separated by spaces.</li>
<li>Depth of evaluation for each URL is <em>top-level page only</em>.</li>
</ul>
</div>
</div>

<form action="." method="post" onsubmit="disable('submit')">

<div class="urls">
{% if form.urls.errors %}{{ form.urls.errors }}{% endif %}
{{ form.urls.label_tag }}<br/>{{ form.urls }}
</div>

<div class="report-title" style="padding-top: 1.5em">
{% if form.title.errors %}{{ form.title.errors }}{% endif %}
{{ form.title.label_tag }}<br/>{{ form.title }}
</div>

{% if enable_dhtmlget %}
<div class="radio-btns">
{% include "dhtml_note.html" %}
{% if form.dhtml.errors %}{{ form.dhtml.errors }}{% endif %}
{{ form.dhtml }} {{ form.dhtml.label_tag }}
</div>
{% endif %}

<div class="submit">
<input type="submit" id="submit" value="Evaluate"/>
</div>

<div>
<input type="hidden" name="formid" value="{{ formid }}"/>
</div>

</form>
{% endblock %}

fae/templates/message.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }}</h1>
{% endblock %}

fae/templates/my_account.html
{% extends "base.html" %}

{% block title %}<title>{{ site.name }}: My Account</title>{% endblock %}

{% block content %}
<h1>My Account</h1>

<div style="margin-top: 0.375em">
<p>Account profile for <strong>{{ username }}</strong></p>
</div>

<form method="post" action=".">

<div style="margin-top: 0.375em">
{% if user_form.first_name.errors %}{{ user_form.first_name.errors }}{% endif %}
<label for="id_first_name">First Name:</label><br/>
{{ user_form.first_name }}
</div>

<div style="margin-top: 0.75em">
{% if user_form.last_name.errors %}{{ user_form.last_name.errors }}{% endif %}
<label for="id_last_name">Last Name:</label><br/>
{{ user_form.last_name }}
</div>

<div style="margin-top: 0.75em">
{% if user_form.email.errors %}{{ user_form.email.errors }}{% endif %}
<label for="id_email">E-mail:</label><br/>
{{ user_form.email }}
</div>

<div style="margin-top: 0.75em">
{% if profile_form.org.errors %}{{ profile_form.org.errors }}{% endif %}
<label for="id_org">Organization:</label><br/>
{{ profile_form.org }}
</div>

<div style="margin-top: 0.75em; margin-bottom: 0.375em">
<input type="submit" value="Update"/>
</div>

</form>

<p>[<a href="/accounts/password/change/">Change Password</a>]</p>

{% endblock %}

fae/templates/report.html
{% extends "base.html" %}

{% block javascript %}
{{ block.super }}
<script type="text/javascript" src="/media/js/prototype.js"></script>
<script type="text/javascript" src="/media/js/external.js"></script>
{% endblock %}

{% block bodytag %}<body onload="addHandlers(); decode('contact')">{% endblock %}

{% block content %}
{{ content|safe }}
{% endblock %}

fae/templates/sidebar.html
{% load menu_item %}

<div id="sidebar">
<div>
<h2 class="hidden">Navigation: Site</h2>
<ul>
{% menu_item index %}
{% if user.is_authenticated %}
{% menu_item archive %}
{% menu_item manage %}
{% endif %}
</ul>
</div>

{% if report %}
<div>
<h2 class="hidden">Navigation: Report Types</h2>
<ul>
{% report_item summary %}
{% ifequal report.pgcount '1' %}
{% report_item page %}
{% else %}
{% report_item sitewide %}
{% report_item page %}
{% prev_next_item %}
{% report_item menu %}
{% endifequal %}
</ul>
</div>

{% if display_sections %}
<div>
<h2 class="hidden">Navigation: Report Sections</h2>
<ul>
{% section_item nav %}
{% section_item text %}
{% section_item auto %}
{% section_item style %}
{% section_item std %}
</ul>
</div>
{% endif %} {# display_sections #}

{% if user.is_authenticated %}
<div>
<h2 class="hidden">Navigation: Download XML Link</h2>
<ul>
{% report_item xml %}
</ul>
</div>
{% endif %}

{% ifequal report.type 'sitewide' %}
<div style="display:none" id="hideAll">
<h2 class="hidden">Page Control: Hide All Lists</h2>
<ul>
<li><a href="javascript:hideAll()">Hide All Lists</a></li>
</ul>
</div>
{% endifequal %}

{% endif %} {# report #}
</div>